### ISSUE TITLE
EvalNewtonsoft is not able to handle a string which gets converted to date type 

### ISSUE THREAD

**Issue by t-tomar** [mikhail-barg/jsonata.net.native#14]
In my code I am using 
var jtoken = JToken.FromObject(new { key, value });

when this jtoken has an embedded property "validFromDatetime": "2023-07-04T00:00:00Z" the EvalNewtonsoft throws error 
Weird token type Date error.

var result = cachedJsonataQuery.EvalNewtonsoft(jtoken);

Is there a work around for this? We are using this library at different places and has worked nicely so far for us

**Comment by mikhail-barg** [comment]
Hi, thanks for highlighting this.

The source of the issue is that Newtonsoft.Json has special tokens for a few .Net classes (`DateTime`, `TimeSpan`, `Guid`, `Uri`) that are not part of JSON specification. 

Therefore when you do `(Newtonsoft.Json.Linq.)JToken.FromObject` on an object containing a property of such type, you'll get a special token, instead of a string token. Therefore I'd suggest to use built-in `Jsonata.Net.Native.Json` token hierarchy whgen possible.

For Newtonsoft I've published a v2.3.0 release, where added conversion from these special tokens to a string via `ToString()` call. But it will use system default CultureInfo, which may result in undesired formats.

Hope current solution is OK for you. Otherwise I may add an optional `CultureInfo` argument for `EvalNewtonsoft()` methods.

**Comment by mikhail-barg** [comment]
Just published a 2.3.1 release with format overrides for `FromNewtonsoft()` call, so it's now possible to customize how the special tokens are formatted via specific ToString() calls.

Hope this wraps the issue. Feel free to reopen in case you see more things are to be implemented.
