### ISSUE TITLE
Performance issue : Datetime , Min & Max Logic

### ISSUE THREAD

**Issue by sureshssb07** [mikhail-barg/jsonata.net.native#18]
Hi Team, Right now i'm using **date time , min & max** in my project but I seen some performance issue while execute on mentioned method and its taking more than 1sec to complete to get result. So I just want to know it is related to json data **(currently used 620KB)** or some code logic behind on this ... 

Ex:
1.  DateTime:
(
$getdatediff := function($date){( 
$cDate := $now(); 
$mDate := $toMillis($date, 'dd/MM/yyyy') ~> $fromMillis('dd/MM/yyyy');  
$iM := $number($toMillis($date, 'dd/MM/yyyy') ~> $fromMillis('MM')); 
$iY := $number($toMillis($date, 'dd/MM/yyyy') ~> $fromMillis('yyyy')); 
$cM := $number($fromMillis($millis(), 'MM')); 
$cY := $number($fromMillis($millis(), 'yyyy')); ($mDate < $cDate) ?  <--Custom Logic--> : <--Custom Logic---> )};

$getdatediff('10021991');
)

2. $max(<--Xpath->.$number())
3. $min(<--Xpath->.$number())

Is there any other approach to get the result quickly ??? 

Thanks in Advance :)

**Comment by mikhail-barg** [comment]
Hi, @sureshssb07 

it's rather difficult to judge on performance issues without having the whole data and seen the actual code. But I'll make some guesses.

1st idea. Yo may want to run the code under profiler, eg Performance Profiler in Visual Studio, or similar tools in other IDEs. This would give you most accurate information on the time your code spend in each function, and hopefully you will be able to find an actual cause of the slowdowns. Still using the profiler and interpreting the results require some actual experience and it's not always clear what is the culprit even with the profiler.

2nd idea. Are you sure that the time is actually spent on executing the query? Not on loading json from file. Not on parsing json,  etc? You may do some quick checks using the [Stopwatch](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.stopwatch?view=net-7.0) to make sure on this.

3rd idea. What Json parser are you using? In case you are using Json.Net or System.Text.Json, there's an additional conversion step from that json DOM to Jsonata.Net.Native.Json. 

4rd idea. Could it be that your code performs parsing/conversion of same json data multiple times? E.g. in case you run multiple queries against the same data — check that the data parsing happens only once.

---

Now, all the ideas above were quite general, and not related to the jsonata queries that you provided. So regarding these queries.

The first one query (the one that is `$getdatediff := function($date){ ...`), looks quite complicated, and it's may be unnecessary so. 
I have only a vague idea of what you are trying to achieve, but a lot of `toMillis() ~> fromMillis()` surely sounds an alarm.

First of all, actual date-time parsing and formatting is a rather expensive operation in .Net (because it does much more under the hood than you may expect, like checking system timzeone and locale, etc). And even if it was not, you'd want to keep your query as simple as possible anyway (if you are concerned about performance).

So for example you may want to change this part:

```
$cDate := $now();
$mDate := $toMillis($date, 'dd/MM/yyyy') ~> $fromMillis('dd/MM/yyyy');
...
($mDate < $cDate) ? ...
```

to the following

```
$cDateMs := $millis();
$mDateMs := $toMillis($date, 'dd/MM/yyyy');
...
($mDateMs < $cDateMs) ? ...
```

This would have the same effect — comparing millis instead of formatted date string — but it saves on not formatting current time to string (which `$now()` does)  and on not calling `$fromMillis()` on a parsed date.

Actually this one is probably even more correct because I have a hard time understanding what would you expect to achieve by comparing dates formatted with (`dd/MM/yyyy`).

So for that case in general, I'd suggest that you try to simplify the query you are using.

---

Regarding the `$min` and `$max`, at the moment I have no specific ideas why these queries may be slow by themselves. I may run those in the profiler, but I need your actual data and queries to run. So you may consider attaching some data for reproduction.

---

Hope that helps.

**Comment by sureshssb07** [comment]
Great 👍  Thanks for your reply :)
