### ISSUE TITLE
Expose jsonata AST

### ISSUE THREAD

**Issue by huangshu91** [mikhail-barg/jsonata.net.native#26]
I have a need where I would like to be able to handle the parsed jsonata AST after the JsonataQuery object has been constructed.  it seems that jsonata-js provides that functionality but I don't see the equivalent in the .Net implementation.  My use case is that the query itself is provided by trusted clients but I need to inspect the query and traverse it to verify and also report on the features.  If there is another way you recommend to support this that you would recommend that would be great too.

**Comment by mikhail-barg** [comment]
Hi @huangshu91. 

I'm afraid, currently there's no introspection api for the query itself in the package.

Could you please point me at the jsonata-js api? Maybe it would be not too complicated to add something similar to my implementation.

**Comment by huangshu91** [comment]
Thanks for the response.  I haven't tried this out myself but I do see the AST exposed here:

https://github.com/jsonata-js/jsonata/blob/9eda3c75c3d0b6cbb0efe1c64a4d5e3ba3c679ca/src/jsonata.js#L2157

Here is where function populating the ast variable:

https://github.com/jsonata-js/jsonata/blob/9eda3c75c3d0b6cbb0efe1c64a4d5e3ba3c679ca/src/parser.js#L338

**Comment by mikhail-barg** [comment]
Hi @huangshu91, sorry for a late answer.

I've been considering your case all that time since, and still haven't come to a decision.

The simple solution would be exposing `JsonataQuery.m_node` field as a property and making all the `Node` class hierarchy (with all object fields) public.

Still this seem to look like exposing internal implementation details and adding those to the library public contract. And I'm not sure if it is reasonable. After all it was not meant to be public, so that implementation could change any time. (And it may happen as current implementation does not seem to allow implementing remaining advanced features of jsonata language).

Adding a separate introspection API (e.g. via some 'visitor pattern' implementation) does not look like having advantages over previous solution, but will add more complexity.

So, right now I'm in a doubt of what to do next.

What I may suggest for you right now (in case you still haven't found a solution yourself), is to use reflection to access `JsonataQuery.m_node` field, and then walk over the nodes knowing names of current Node classes. Which could be a kind of a boilerplate. But in case you need to only check for some "bad" patterns in queries, it might happen so that you'll only need to look for specific cases, and not do a fully-fledged processing there.

Please tell me if it would suit your needs or you are still interested in having the query AST exposed. If latter, could you please provide a bit more info on your use-case, so that I could convince myself that it really worth exposing library internals, or maybe come with some other solution.

**Comment by mikhail-barg** [comment]
@huangshu91 I've released a v2.7.0 package with new DOM API, as discussed in #28.

So you may now call `query.GetDOM()` and get an underlying DOM structure for a query.

A bit more details are here: https://github.com/mikhail-barg/jsonata.net.native?tab=readme-ov-file#query-dom-introspection-and-query-creation-via-dom

Some samples are here: https://github.com/mikhail-barg/jsonata.net.native/blob/master/src/Jsonata.Net.Native.Tests/DomTests.cs

Please note that I've changes namespaces for the `Node` classes, renamed some of the Nodes, and most of the fields to make them more consistent for a public API. 

So this would be a breaking change for you, if you are currently using reflection to access private Node hierarchy as I proposed above. Hope this would not be a too much of a problem for you.

Please check if this new API suits your needs.
