### ISSUE TITLE
How to add line breaks?

### ISSUE THREAD

**Issue by JobaDiniz** [mikhail-barg/jsonata.net.native#32]
I'm trying to join strings with line breaks, but it does not work.

![image](https://github.com/user-attachments/assets/d9ac4680-f0a0-42bd-b3f4-b844d884c1b2)

**Comment by mikhail-barg** [comment]
@JobaDiniz have you tried quoting the `\n` string? try using double quotes. 

If does not work, please provide data source and query here as test, so I could reproduce the problem locally without manually entering the code.

**Comment by JobaDiniz** [comment]
I've tried: `\n` and `'\n'`.

I've also tried in the https://try.jsonata.org/ and it does not work either.

**source**
```json
{
  "messages": [
    {
      "role": "Assistant",
      "message": "assistant"
    },
    {
      "role": "User",
      "message": "user"
    },
    {
      "role": "System",
      "message": "system"
    },
    {
      "role": "User",
      "message": "uuuu"
    }
  ]
}
```

**jsonata**
```jsonata
(
    $array := $filter(messages, function($message){ $message.role != 'System'});
    $array := $map($array, function($message){$message.role & ': ' & $message.message});
    $join($array, '\n')
)
```

**Comment by mikhail-barg** [comment]
> "Assistant: assistant\nUser: user\nUser: uuuu"

This looks pretty much like expected. You get a JSON string which can't have plain line breaks, because line breaks are escaped with `\n` in JSON. https://www.json.org/json-en.html 

But this escaping is done when (pretty)printing the reuslting json in the excersizer window (see https://github.com/mikhail-barg/jsonata.net.native/blob/36eb84f5db9501a9df0070a79d2822278929a0f6/src/Jsonata.Net.Native/Json/JValue.cs#L86). So the original string accessible via c# code should have natural line breaks.

Anyway, could you elaborate more on what you expect to achieve?

**Comment by JobaDiniz** [comment]
Using quotes worked. You were correct.
Thanks.
